name: template-project
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
    - conda-forge::r-base=4.0.2
    - bioconda::fastqc=0.11.8
    # add others as needed- these are just examples